---
azure:
  #subscriptions: []
  locations: []

  resourceTags: []
  resourceGroupTags: []

collectors:
  general: {}

  resource: {}

  quota: {}

  defender: {}

  resourceHealth: {}

  iam: {}

  graph: {}

  costs: {}

  budgets: {}

  reservation: {}

  portscan:
    scanner:
      parallel: 2
      threads: 1000
      timeout: 5
      ports: [22,80,443,3389]
